USE TRAINING_01

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT

--DROP TABLE IF EXISTS Moves
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Moves' AND TABLE_SCHEMA = 'dbo')
DROP TABLE dbo.Moves;
GO

CREATE TABLE dbo.Moves
	(
	INSERTED_DATE date NOT NULL,
	ID_MOVE int NOT NULL IDENTITY (1, 1),
	SENDER_CODE int NOT NULL,
	RECEIVER_CODE int NOT NULL,
	GOOD_CODE nvarchar(10) NOT NULL,
	GOOD_DESCR nvarchar (MAX) NULL,
	NETTO decimal(10,2) NOT NULL, 
	PRICE decimal(10,2) NOT NULL,
	TAX decimal(5,2) NULL,
	STATUS nvarchar(2) NULL,
	VEHICLE nvarchar(20) NULL,
	UPDATED_DATE date NULL
	)  ON [PRIMARY]
GO





/***** We set a [UPDATED_DATE] field into the last date of modification ******/  
CREATE OR ALTER TRIGGER dbo.Moves_Update   
ON dbo.Moves
FOR UPDATE   
AS

DECLARE @OldVal int
SELECT @OldVal = ID_MOVE from inserted

UPDATE [dbo].[Moves]
SET [UPDATED_DATE] = getdate()
WHERE [ID_MOVE] = @OldVal
GO

ALTER TABLE dbo.Moves ADD CONSTRAINT
	PK_Moves PRIMARY KEY CLUSTERED 
	(
	ID_MOVE
	) WITH( STATISTICS_NORECOMPUTE = OFF, 
	        IGNORE_DUP_KEY = OFF, 
			ALLOW_ROW_LOCKS = ON, 
			ALLOW_PAGE_LOCKS = ON) 
		ON [PRIMARY]

GO

CREATE NONCLUSTERED INDEX IX_Moves_Sender ON dbo.Moves
	(
	SENDER_CODE
	) WITH( STATISTICS_NORECOMPUTE = OFF, 
	        IGNORE_DUP_KEY = OFF, 
			ALLOW_ROW_LOCKS = ON, 
			ALLOW_PAGE_LOCKS = ON) 
		ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX IX_Moves_Receiver ON dbo.Moves
	(
	RECEIVER_CODE
	) WITH( STATISTICS_NORECOMPUTE = OFF, 
	        IGNORE_DUP_KEY = OFF, 
			ALLOW_ROW_LOCKS = ON, 
			ALLOW_PAGE_LOCKS = ON) 
		ON [PRIMARY]
GO

ALTER TABLE dbo.Moves ADD CONSTRAINT 
    DF_Moves_INSERTED_DATE DEFAULT (getdate()) FOR INSERTED_DATE
GO

ALTER TABLE dbo.Moves ADD CONSTRAINT
	FK_Moves_Agents_Receiver FOREIGN KEY
	(
	RECEIVER_CODE
	) REFERENCES dbo.Agents
	(
	ID_CONTRAGENT
	) 
	 ON UPDATE  NO ACTION
	 ON DELETE  NO ACTION 
	
GO

ALTER TABLE dbo.Moves ADD CONSTRAINT
	FK_Moves_Agents_Sender FOREIGN KEY
	(
	SENDER_CODE
	) REFERENCES dbo.Agents
	(
	ID_CONTRAGENT
	) 
	 ON UPDATE  NO ACTION
	 ON DELETE  NO ACTION 
	
GO


/****** It's impossible to have a transport from particular sender to particular receiver in one day  *******/
CREATE UNIQUE NONCLUSTERED INDEX IX_Moves_Sender_Receiver ON dbo.Moves
	(
	SENDER_CODE,
	RECEIVER_CODE,
    STATUS
	) WITH( STATISTICS_NORECOMPUTE = OFF, 
	        IGNORE_DUP_KEY = OFF, 
			ALLOW_ROW_LOCKS = ON, 
			ALLOW_PAGE_LOCKS = ON) 
		ON [PRIMARY]
GO

ALTER TABLE dbo.Moves SET (LOCK_ESCALATION = TABLE)
GO
