USE [O_SYDOR_MODULE_2]

ALTER TABLE dbo.Agents ADD CONSTRAINT
	DF_Agents_COUNTRY_COD DEFAULT 840 FOR COUNTRY_COD
GO


ALTER TABLE dbo.Agents ADD CONSTRAINT 
    DF_Agents_INSERTED_DATE DEFAULT (getdate()) FOR INSERTED_DATE
GO

ALTER TABLE dbo.Agents ADD CONSTRAINT
	PK_Agents PRIMARY KEY CLUSTERED 
	(
	ID_CONTRAGENT
	) WITH( STATISTICS_NORECOMPUTE = OFF, 
	        IGNORE_DUP_KEY = OFF, 
			ALLOW_ROW_LOCKS = ON, 
			ALLOW_PAGE_LOCKS = ON) 
	  ON [PRIMARY]

GO

CREATE NONCLUSTERED INDEX IX_Agents ON dbo.Agents
	(
	ID_CONTRAGENT
	) WITH( STATISTICS_NORECOMPUTE = OFF, 
	        IGNORE_DUP_KEY = OFF, 
			ALLOW_ROW_LOCKS = ON, 
			ALLOW_PAGE_LOCKS = ON) 
	  ON [PRIMARY]
GO

ALTER TABLE dbo.Agents SET (LOCK_ESCALATION = TABLE)
GO