USE [O_SYDOR_MODULE_2]

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT

--DROP TABLE IF EXISTS Moves
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Moves' AND TABLE_SCHEMA = 'dbo')
DROP TABLE dbo.Moves;
GO

CREATE TABLE dbo.Moves
	(
	INSERTED_DATE date NOT NULL,
	ID_MOVE int NOT NULL IDENTITY (1, 1),
	SENDER_CODE int NOT NULL,
	RECEIVER_CODE int NOT NULL,
	GOOD_CODE nvarchar(10) NOT NULL,
	GOOD_DESCR nvarchar (MAX) NULL,
	NETTO decimal(10,2) NOT NULL, 
	PRICE decimal(10,2) NOT NULL,
	TAX decimal(5,2) NULL,
	STATUS nvarchar(2) NULL,
	VEHICLE nvarchar(20) NULL,
	UPDATED_DATE date NULL
	)  ON [PRIMARY]
GO
