USE O_SYDOR_MODULE_2
GO

CREATE OR ALTER VIEW VAgents
AS
SELECT   [INSERTED_DATE]
		,[ID_CONTRAGENT]
		,[EDRPOU]
		,[SHORTNAME]
		,[FULLNAME]
		,[DIRECTOR]
		,[CAPITAL]
		,[FOUNDED]
		,[COUNTRY_COD]
		,[PREV_REC]
		,[UPDATED_DATE]
FROM [O_SYDOR_MODULE_2].[dbo].[Agents]
GO

CREATE OR ALTER VIEW VAgentsCheck
AS
SELECT   [INSERTED_DATE]
		,[ID_CONTRAGENT]
		,[EDRPOU]
		,[SHORTNAME]
		,[FULLNAME]
		,[DIRECTOR]
		,[CAPITAL]
		,[FOUNDED]
		,[COUNTRY_COD]
		,[PREV_REC]
		,[UPDATED_DATE]
FROM [O_SYDOR_MODULE_2].[dbo].[Agents]
WHERE LEFT([EDRPOU],3) = '133'
WITH CHECK OPTION
GO

CREATE OR ALTER VIEW VMoves AS
SELECT [INSERTED_DATE]
      ,[ID_MOVE]
      ,[SENDER_CODE]
      ,[RECEIVER_CODE]
      ,[GOOD_CODE]
      ,[GOOD_DESCR]
      ,[NETTO]
      ,[PRICE]
      ,[TAX]
      ,[STATUS]
      ,[VEHICLE]
      ,[UPDATED_DATE]
  FROM [O_SYDOR_MODULE_2].[dbo].[Moves]
GO
