/****** CREATE DATABASE WITH DEFAULT FILEGROUPS AND DEFAULT PATHS. 
DATABASE NAME osydor_module_2. 
ALL OBJECTS BELOW SHOULD BE CREATED IN THIS DATABASE ******/


/****** CREATE A PAIR OF TABLES (PARENT AND CHILD)
EACH TABLE SHOULD HAVE AT LEAST 10 COLUMNS WITH MEANINGFUL NAMES.
+TWO MANDATORY COLUMNS: INSERTED_DATE AND UPDATED_DATE
+1. TABLE SHOULD HAVE COLUMNS WITH 3 MAIN DATA TYPES (FOR STORING TEXT, NUMBER, DATES)
+2. CREATE A PRIMARY KEY, A UNIQUE KEY, CHECK CONSTRAINT ON THE TABLE
+3. CREATE A FOREIGN KEY FOR THE CHILD TABLE
+4. CREATE A TRIGGER FOR UPDATE STATEMENT. THE TRIGGE SHOULD MODIFY UPDATED_DATE
+5. CREATE A VIEW FOR EACH TABLE
+6. CREATE A VIEW WITH CHECK_OPTION
+4. CREATE ANOTHER PAIR OF TABLES 
(THE 1ST UP TO 15 COLUMNS, THE SECOND TABLE HAS THE SAME STRUCTURE 
AND INCLUDE ADDITIONAL COLUMNS: TYPE OF OPERATION, DATE OF OPERATION)
THE COLUMNS SHOULD HAVE MEANINGFUL NAMES.
- CREATE 3 TRIGGERS FOR THE FIRST TABLE (FOR OPERATIONS INSERT, UPDATE, DELETE)
5. DEVELOP THE SCRIPT FOR TASKS ##3 AND 4 TO CHECK THE VALID BEHAVIOUR FOR ALL CONSTRAINTS CREATED.
IN ADDITION DEVELOP A QUERY TO CHECK THE CORRECT RECORDS INSERTED INTO THE TABLE 
(THE RECORDS THAT NOT VIOLATE ANY CONSTRAINTS ON THE TABLE)
6. CREATE THE SYNONYMS FOR OBJECTS CREATED IN TASKS #3 AND #4 ABOVE 
IN THE DATABASE EDUCATION (CREATE A SCHEMA WITH THE NAME OSYDOR, 
CREATE 4 SCRIPTS TO RETRIVE DATA FROM SYNONYMS
******/

--new string 1
